
name: Custom Action Workflow

on:
  push:
    branches:
       - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2

    - name: Run execute my script
      run: |  
        echo "This is a custom script."
        echo "It will run on every push to the main branch and every hour."
